export const GET_RANDOM_NUMBER_FACT = 'GET_RANDOM_NUMBER_FACT';
export const GET_RANDOM_NUMBER_FACT_STARTED = 'GET_RANDOM_NUMBER_FACT_STARTED';
export const GET_RANDOM_NUMBER_FACT_SUCCESS = 'GET_RANDOM_NUMBER_FACT_SUCCESS';
export const GET_RANDOM_NUMBER_FACT_FAILURE = 'GET_RANDOM_NUMBER_FACT_FAILURE';
export const SAVE_RANDOM_NUMBER_FACT = 'SAVE_RANDOM_NUMBER_FACT';
